//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WF_DZ_3 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WF_DZ_3.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Применить.
        /// </summary>
        internal static string button_color {
            get {
                return ResourceManager.GetString("button_color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбить итоговый общий чек..
        /// </summary>
        internal static string cheсk {
            get {
                return ResourceManager.GetString("cheсk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменение цвета формы.
        /// </summary>
        internal static string color_info {
            get {
                return ResourceManager.GetString("color_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Итоговый чек мини-кафэ..
        /// </summary>
        internal static string endPrice_cafe {
            get {
                return ResourceManager.GetString("endPrice_cafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Итоговый чек топливо..
        /// </summary>
        internal static string endPrice_fuel {
            get {
                return ResourceManager.GetString("endPrice_fuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Итоговый общий чек..
        /// </summary>
        internal static string endPrice_total {
            get {
                return ResourceManager.GetString("endPrice_total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбор топлива..
        /// </summary>
        internal static string fuel {
            get {
                return ResourceManager.GetString("fuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите необходимое количество топлива\nили имеющуюся сумму..
        /// </summary>
        internal static string option {
            get {
                return ResourceManager.GetString("option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена топлива за 1 литр..
        /// </summary>
        internal static string price_fuel {
            get {
                return ResourceManager.GetString("price_fuel", resourceCulture);
            }
        }
    }
}
